---

- name: PLAY 1
  hosts: apic
  connection: local
  gather_facts: no
  
  tasks:
    - name: TASK 1 - GATHER TENANTS
      TACACS_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ TACACS_username }}"
        password: "{{ TACACS_password }}"
        validate_certs: no
        state: query
     
    - name: TASK 2 - GATHER APs
      TACACS_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ TACACS_username }}"
        password: "{{ TACACS_password }}"
        validate_certs: no
        state: query
    
    - name: TASK 3 - GATHER EPGS
      TACACS_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ TACACS_username }}"
        password: "{{ TACACS_password }}"
        validate_certs: no
        ap: app-v
        state: query
