---

- name: PLAY 3
  hosts: apic
  connection: local
  gather_facts: no
  
  tasks:
  
    - name: download all static bindings
      aci_static_binding_to_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        # tenant: 'datacenter'
        # ap: "mpog"
        # epg: "prd-dmz"
        leafs: [102, 105]
        interface_type: vpc
        # interface: 'leaf102_105_ban-cs_ports_1-ports-44_PolGrp'
        # pod_id: 1
        # encapID: "{{ item.encapID }}"
        # deploy_immediacy: immediate
        state: query
      delegate_to: localhost
      register: Paths
      # with_items: "{{ stuff }}"
      
    - name: pad maken met dn,tDn, encap en mode
      set_fact:
        # pad: "{{ Paths | json_query('current[*].fvRsPathAtt.attributes.{dn: dn, tDn: tDn, encap: encap | regex_replace('vlan-(?P<vlanid>.*  )', '\\g<vlanid>') , mode: mode}') }}"
        pad: "{{ Paths | json_query('current[*].fvRsPathAtt.attributes.{dn: dn, tDn: tDn, encap: encap , mode: mode}') }}"
        # pad: "{{ Paths | json_query('current[*].fvRsPathAtt.attributes.dn') }}"
      
    - name: pad filteren op topology/pod-1/protpaths-102-105/pathep-[leaf102_105_ban-cs_ports_1-ports-44_PolGrp]
      set_fact: 
        pad: "{{ (pad | selectattr('tDn','equalto','topology/pod-1/protpaths-102-105/pathep-[leaf102_105_ban-cs_ports_1-ports-44_PolGrp]') | list ) }}"
         


    - name: maak lijst
      set_fact: 
        lijst: []

    - name: vul lijst
      set_fact:
        lijst: "{{ lijst  + [{ 'tenant': item.dn | regex_replace('uni\\/tn-(?P<tenant>.*)\\/ap-(?P<ap>.*)\\/epg-(?P<epg>.*)\\/rs.*', '\\g<tenant>'),  'ap': item.dn | regex_replace('uni\\/tn-(?P<tenant>.*)\\/ap-(?P<ap>.*)\\/epg-(?P<epg>.*)\\/rs.*', '\\g<ap>'),  'epg': item.dn | regex_replace('uni\\/tn-(?P<tenant>.*)\\/ap-(?P<ap>.*)\\/epg-(?P<epg>.*)\\/rs.*', '\\g<epg> '), 'tDn': item.tDn , 'encap': item.encap, 'encapID': item.encap | regex_replace('vlan-(?P<vlan>.*)', '\\g<vlan>') }] }}"
        # lijst: "{{ lijst  + [{ 'tenant': item.dn | regex_replace('uni\\/tn-(?P<tenant>.*)\\/ap-(?P<ap>.*)\\/epg-(?P<epg>.*)\\/rs.*', '\\g<tenant>'), 'encap':  item.encap | quote }] }}"
         # tDn: item.tDn | quote, , encap: item.encap, encapID: item.encap | regex_replace('vlan-(?P<vlan>.*)', '\\g<vlan>')
      with_items: "{{ pad }}"
      
      
    - name: maak epgs met vlan id 
      set_fact: 
        epgs: []
        
    - name: Filter op dmz
      set_fact: 
        epgs: "{{ epgs + [ item ] }}"
      with_items: "{{ lijst }}"
      when: item.encapID | int  >= 498 and item.encapID | int < 600
      
    - name: test
      debug: var=epgs
      
    - name: test
      debug: var="{{ epgs | length }}"
      
      
