---

- name: PLAY 1
  hosts: apic
  connection: local
  gather_facts: no
  
  tasks:
    - name: TASK 1 - GATHER TENANTS
      aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query
     
    - name: TASK 2 - GATHER APs
      aci_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query
    
    - name: TASK 3 - GATHER EPGS
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        ap: app-v
        state: query
