---

- name: PLAY 2
  hosts: apic
  connection: local
  gather_facts: no
  
  tasks:
    - name: TASK 1 - List of APP profiles for tenants
      aci_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: datacenter
        state: query
      register: prod_apps
    
    - name: TASK 2 - Create list of just APP names
      set_fact:
        apps: "{{ prod_apps | json_query('current[0].fvTenant.children[*].fvAp.attributes.name') }}"
        epgs: "{{ prod_apps | json_query('current[0].fvTenant.children[*].fvAp.children[*].fvAEPg.attributes.name') }}"

    - name: Print list of apps in tenant
      debug: var=apps
      debug: var=epgs