---

- name: PLAY 3
  hosts: apic
  connection: local
  gather_facts: no
  
  tasks:
    - name: TASK 1 - List of APP profiles for tenants
      aci_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query
      register: prod_ap

    - name: TASK 2 - Create list of just APP names
      set_fact:
        apps: "{{ prod_ap | json_query('current[*].fvAp.attributes.name') }}"

    - name: TASK 3a - List of AP profiles for tenants
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: datacenter
        state: query
      register: prod_apps        
      
    # - name: TASK 3 - List of AP profiles for tenants
      # aci_epg:
        # hostname: "{{ inventory_hostname }}"
        # username: "{{ aci_username }}"
        # password: "{{ aci_password }}"
        # validate_certs: no
        # ap: "{{ item }}"
        # tenant: datacenter
        # state: query
      # with_items: "{{ apps }}"
      # register: prod_apps
      
    
    - name: TASK 2 - Create list of just APP names
      set_fact:
        #apps: "{{ prod_apps | json_query('current[0].fvTenant.children[*].fvAp.attributes.name') }}"
        apps: "{{ prod_apps | json_query('current[0].fvTenant.children[*].fvAp.attributes.name') }}"
        #epgs: "{{ prod_apps | json_query('current[0].fvTenant.children[*].fvAp.children[*].fvAEPg.attributes.name') }}"
        #epgs: "{{ prod_apps | json_query('current[0].fvAp.children[*].fvAEPg.attributes.name') }}"
        # epgs: "{{prod_apps | json_query('result.current[0].fvTenant.children[*].fvAp.children[*].fvAEPg.attributes.name') }}"
        epgs: "{{ prod_apps | json_query('current[0].fvTenant.children[*].fvAp.children[*].fvAEPg.attributes.name') }}"

    - name: test 2 test
      debug: var=apps

      
    - name: TASK 2 debug
      debug: var=epgs
    
    - name: epg-to-domain
      aci_epg_to_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query

    - name: aci_static_binding_to_epg
      aci_static_binding_to_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: datacenter
        ap: wec
        epg: tst-dmz
        leafs: 102-105
        interface: leaf102_105_switch_ports_1-ports-46_PolGrp
        output_level: debug
        state: query
        
    # - name: "Display all ports from cluster1"
      # # debug:
        # # var: item
      # set_fact: item
      # loop: "{{ prod_apps | json_query(server_name_cluster1_query) }}"
      # vars:
        # # server_name_cluster1_query: "current[0].fvTenant.children[*].fvAp.children[*].fvAEPg.attributes.{name1: name, descr: desrc}"
        # server_name_cluster1_query: "current[0].fvTenant.children[*].fvAp.{APName: attributes.name, EPGName: children[*].fvAEPg.attributes.name }"
        
            # # server_name_cluster1_query: "domain.server[?cluster=='cluster2'].{name: name, port: port}"
    # - name: test 2 test
      # debug: var=prod_apps
      
      
      
      
    # - name: TASK 3 - Create list of just APP names
      # set_fact:
        # #ap_epg: "{{ ap_epg|default([]) + [ {'name': item.fvTenant.children.fvAp.attributes.name'), 'gender': item.fvTenant.children.fvAp.children.fvAEPg.attributes.name} ] }}"
        # ap_epg: "{{ ap_epg | default([]) + [ { 'item': item } ] }}"
      # with_items: "{{ prod_apps.current | map(attribute='name') | list  }}"

    # - name: Print list of apps in tenant
      # debug: var=ap_epg
    
   # - name: test1
    #    test : "{{ test | default([]) + [ { 'item': item } ] }}"
    #  with_items: 
    #    - "{{ prod_apps.current | map(attribute='current') | map('from_json') | map(attribute='fvAp') | sum(start=[]) | map(attribute='fvAEPg') | list }}"
    #  
    #- name tesr
    #  debug: var=test
      
