---

- hosts: localhost
  vars:
    cidr: "{{ var_cidr | regex_replace('-.*$','') }}"
    num: "{{ var_num }}"
    network: "{{ var_network }}"
    test: "1"
    
    Virtual: False
    Physical: False
    Domain: "{{ var_Domain | regex_replace('-.*$','') | trim }}"
    Tier: "{{ var_Tier | regex_replace('^[^-]*-','') | trim }}"
  connection: local
  gather_facts: no
  
  tasks:
   - debug: var=var_AppName

   - debug: var=var_AppDesc
   - debug: var=var_Domain
   - debug: var=Domain

   - set_fact:
        DMZ: "{{ True if ((Domain=='exid.umcn.nl') or (Domain=='exidtest.umcn.nl')) else False }}"
   - debug: var=DMZ

   - set_fact:
        Omgeving: "{{ 'prd' if ((Domain=='exid.umcn.nl') or (Domain=='Oud L2' ) or (Domain=='umcn.nl')) else 'tst' }}"

   - debug: var=Omgeving
   - set_fact:
        L2: "{{ True if ((Domain=='Oud L2') or DMZ ) else False }}"

   - debug: var=L2
   
   - debug: var=var_Tier
   - debug: var=Tier
   - debug: var=var_TAP
   - debug: var=var_PhysVirt

   - set_fact:
        Virtual: True
     when: '"Virtual" in var_PhysVirt'
   - set_fact:
        Physical: True
     when: '"Physical" in var_PhysVirt'
   - debug: var=Virtual
   - debug: var=Physical

   - debug: var=var_L2Vlan
   - fail:
       msg: "Domein \"Oud L2\" geselecteerd maar geen VLAN ID meegegeven!"
     when: (
          ((var_L2Vlan is undefined)
          or
          (var_L2Vlan is none)
          or
          (var_L2Vlan | trim == ''))
          and (Domain == 'Oud L2')
        )
   - debug: var=var_Hosts
   - set_fact:
        net_overhead: "{{5 if DMZ else 3 }}"
   - debug: var=net_overhead
   - debug: var=networks
   
   - set_fact:
        num_hosts: "{{var_Hosts|int + net_overhead |int }}"
   - debug: var=num_hosts
   - set_fact:
          net: "{%for po2 in range(3,12)%}{{ po2 if (2|pow(po2)|int>=num_hosts|int) else None }} {%endfor%}"
   - debug: var=net
   - debug: var=net.split()
   - debug: var=net.split()|first
   - set_fact:
        CIDR:"{{ 32 - net.split()|first|int }}
   - debug: var=CIDR
   - debug: var=net.split()[0]|int
# Applicatie Naam           = var_AppName
# Applicatie Omschrijving   = var_AppDesc
# Domein                    = var_Domain
# Type                      = var_Tier
# Omgeving                  = var_TAP
# Gateway IP
# NetMask
# Virtueel/Fysiek           = var_PhysVirt
# VLAN L2                   = var_L2Vlan
