---

- hosts: localhost
  vars:
    cidr: "{{ var_cidr | regex_replace('-.*$','') }}"
    num: "{{ var_num }}"
    network: "{{ var_network }}"
    test: "1"
    Virtual: False
    Physical: False
    Domain: "{{ var_Domain | regex_replace('-.*$','') | trim }}"
    Tier: "{{ var_Tier | regex_replace('-.*$','') | trim }}"
  connection: local
  gather_facts: no
  
  tasks:
   - debug: var=var_AppName

   - debug: var=var_AppDesc
   - debug: var=var_Domain
   - debug: var=Domain
   - debug: var=var_Tier
   - debug: var=Tier
   - debug: var=var_TAP
   - debug: var=var_PhysVirt
   - set_fact:
        Virtual: True
     when: '"Virtual" in var_PhysVirt'
   - set_fact:
        Physical: True
     when: '"Physical" in var_PhysVirt'
   - debug: var=Virtual
   - debug: var=Physical
   - debug: var=var_L2Vlan
   - fail:
     when: (
          ((var_L2Vlan is undefined)
          or
          (var_L2Vlan is none)
          or
          (var_L2Vlan | trim == ''))
          and (Domain == 'Oud L2')
        )

     
# Applicatie Naam           = var_AppName
# Applicatie Omschrijving   = var_AppDesc
# Domein                    = var_Domain
# Type                      = var_Tier
# Omgeving                  = var_TAP
# Gateway IP
# NetMask
# Virtueel/Fysiek           = var_PhysVirt
# VLAN L2                   = var_L2Vlan
