---
- hosts: Infoblox
  vars:
    nios_provider:
      host: "{{ inventory_hostname }}"
        username: "{{ TACACS_username }}"
        password: "{{ TACACS_password }}"
  connection: local
  gather_facts: no

  tasks:
   - name: delete host record
     nios_host_record:
       name: host.ansiblezone.umcn.nl
       view: Internal
       state: absent
       provider: "{{ nios_provider }}"
