---

- name: PLAY 3
  hosts: apic
  connection: local
  gather_facts: no
  
  tasks:
  

    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      include_vars:
        file: stuff.json
        name: stuff

    - name: TASK 2 - Create list of just APP names
      set_fact:
        stuff: "{{ stuff | json_query('ACI.DMZEPG[*]') }}"
       
    - name: test 2 test
      debug: var=stuff

      
    - name: Remove an existing physical domain l2ext_banc_dom_datacenter to EPG binding
      aci_epg_to_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        domain: l2ext_banc_dom_datacenter
        domain_type: l2dom
        deploy_immediacy: lazy
        resolution_immediacy: immediate
        state: absent
      delegate_to: localhost
      with_items: "{{ stuff }}"      

    # - name: Remove an existing physical domain l2ext_ban-cs_dom_datacenter to EPG binding
      # aci_epg_to_domain:
        # hostname: "{{ inventory_hostname }}"
        # username: "{{ aci_username }}"
        # password: "{{ aci_password }}"
        # validate_certs: no
        # tenant: "{{ item.tenant }}"
        # ap: "{{ item.ap }}"
        # epg: "{{ item.epg }}"
        # domain: l2ext_ban-cs_dom_datacenter
        # domain_type: l2dom
        # deploy_immediacy: lazy
        # resolution_immediacy: immediate
        # state: absent
      # delegate_to: localhost
      # with_items: "{{ stuff }}"

    - name: remove aci_static_binding_to_epg leaf102_105_switch_ports_1-ports-46_PolGrp
      aci_static_binding_to_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        leafs: [102, 105]
        interface_type: vpc
        interface: 'leaf102_105_switch_ports_1-ports-46_PolGrp'
        pod_id: 1
        encap_id: "{{ item.encap_id }}"
        deploy_immediacy: immediate
        state: absent
      delegate_to: localhost
      with_items: "{{ stuff }}"
      

    - name: add an existing physical domain l2ext_dmzfw_dom_datacenter to EPG binding
      aci_epg_to_domain:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        domain: l2ext_dmzfw_dom_datacenter
        domain_type: l2dom
        deploy_immediacy: lazy
        resolution_immediacy: immediate
        state: present
      delegate_to: localhost
      with_items: "{{ stuff }}"

    # - name: remove aci_static_binding_to_epg leaf102_105_ban-cs_ports_1-ports-44_PolGrp
      # aci_static_binding_to_epg:
        # hostname: "{{ inventory_hostname }}"
        # username: "{{ aci_username }}"
        # password: "{{ aci_password }}"
        # validate_certs: no
        # tenant: "{{ item.tenant }}"
        # ap: "{{ item.ap }}"
        # epg: "{{ item.epg }}"
        # leafs: [102, 105]
        # interface_type: vpc
        # interface: 'leaf102_105_ban-cs_ports_1-ports-44_PolGrp'
        # pod_id: 1
        # encap_id: "{{ item.encap_id }}"
        # deploy_immediacy: immediate
        # state: absent
      # delegate_to: localhost
      # with_items: "{{ stuff }}"
      
    - name: add aci_static_binding_to_epg leaf102_105_dmzfwp01_ports_1-ports-36_PolGrp
      aci_static_binding_to_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        leafs: [102, 105]
        interface_type: vpc
        interface: 'leaf102_105_dmzfwp01_ports_1-ports-36_PolGrp'
        pod_id: 1
        encap_id: "{{ item.encap_id }}"
        deploy_immediacy: immediate
        state: present
      delegate_to: localhost
      with_items: "{{ stuff }}"

    - name: add aci_static_binding_to_epg leaf102_105_dmzfwp02_ports_1-ports-46_PolGrp
      aci_static_binding_to_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        leafs: [102, 105]
        interface_type: vpc
        interface: 'leaf102_105_dmzfwp02_ports_1-ports-46_PolGrp'
        pod_id: 1
        encap_id: "{{ item.encap_id }}"
        deploy_immediacy: immediate
        state: present
      delegate_to: localhost
      with_items: "{{ stuff }}"


 