---

- hosts: masterblox.man.umcn.nl
  vars:
    cidr: "{{ var_cidr | regex_replace('-.*$','') }}"
    num: "{{ var_num }}"
    test: "1"
    network: "{{ var_network }}"
    nios_provider:
      host: "{{ inventory_hostname }}"
      username: "{{ TACACS_username }}"
      password: "{{ TACACS_password }}"
  connection: local
  gather_facts: no
  
  tasks:
  # - debug: var={{ test | type_debug }}
  # - set_fact:
  #      test1: "{{test| int}}"
  # - debug: var={{ test1 | type_debug }}
   
   - name: Gather info
     set_fact:
        ipv4addr: "{{ lookup('nios_next_ip', '10.25.4.0/22', num=num|int, exclude=['10.25.4.39'],provider=nios_provider) }}"
        net: "{{ lookup('nios_next_network', network, cidr=cidr|int, num=num|int, provider=nios_provider) }}"
        host:  "{{ lookup('nios', 'record:host', filter={'name': 'umcinfrabep02.umcn.nl'}, provider=nios_provider) }}"
        # mac:   "{{ host | to_json | from_json | json_query('ipaddrs[0].mac') }}"
   - debug: var=net
   - debug: var=ipv4addr
   - name: Gather info
     set_fact:
        # ipv4addr: "{{ lookup('nios_next_ip', '10.0.0.0/23', provider=nios_provider)[0] }}"
        # host:  "{{ lookup('nios', 'record:host', filter={'name': 'umcinfrabep02.umcn.nl'}, provider=nios_provider) }}"
        mac:   "{{ host | json_query('ipv4addrs[0].mac') }}"
   - name: Print info
     # debug: var=ipv4addr
     debug: var=host
   - name: Print info
     # debug: var=ipv4addr
     debug: var=mac