---

- name: lookups in variables vs. lookups in facts
  hosts: localhost
  vars:
    nios_provider:
      host: 10.0.1.241
      username: ccvcv_man
      password: 92meiland
    # connection: local
    dns_views: "{{ lookup('nios', 'record:host', filter={'name': 'host.ansiblezone.umcn.nl'}, return_fields=['comment','extattrs','ipv4addrs','ipv6addrs','name', 'view'], provider=nios_provider) }}"
    var_networks: "{{ lookup('nios', 'network', filter={'*OSPF Area': '302'}, return_fields=['comment','extattrs','network', 'network_view'], provider=nios_provider) }}"
    var_time: "{{lookup('pipe', 'date \"+%H:%M:%S\"')}}"
    var_ips: "{{ lookup('nios_next_ip', '10.0.0.0/23',num=20 , provider=nios_provider) }}"
  tasks:
    - debug: var=dns_views
    - name: create host record
      nios_host_record:
           name: host.ansiblezone.umcn.nl
           view: Internal
           ipv4addrs: 
             - ipv4addr: "{{ lookup('nios_next_ip', '10.0.0.0/23',num=10 , provider=nios_provider)[0] }}"
           ipv6addrs:
             - ipv6addr: fd00::2
           ttl: 3600
           extattrs:
             Site: Test Site
           comment: Created with Ansible
           state: present
           provider: "{{ nios_provider }}"
    - debug: var=var_time
    - debug: var=dns_views
    - name: delete host record
      nios_host_record:
       name: host.ansiblezone.umcn.nl
       view: Internal
       state: absent
       provider: "{{ nios_provider }}"
    # - command: sleep 2
    - debug: var=var_time
    - debug: var=dns_views
    - debug: var=var_ips
    - debug: var=var_networks[0]['network'].split('/')[1]